spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tesilvestretfi
    username: root
    password: localhost
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
